In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from keras.utils import np_utils
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import mean_squared_error

Using TensorFlow backend.


In [2]:
data = pd.read_csv("data_company22.csv",index_col=0, header=0, thousands=',',encoding='cp949')

In [3]:
list(data)

['매출액',
 'EBIT',
 'Op.EBIT',
 'EBITDA',
 '금융비용',
 '순금융비용',
 '세전계속사업이익',
 '당기순이익',
 '자산총계',
 '부채총계',
 '자본총계',
 '(납입자본금)',
 '총차입금',
 '단기차입금',
 '유동성장기부채',
 '장기차입금',
 '현금성자산',
 '순차입금',
 '조정총차입금',
 '운전자본',
 '매출채권',
 '재고자산',
 '매입채무',
 '총영업활동현금흐름(OCF)',
 '비현금항목 조정',
 '운전자본투자',
 '매출채권 등의 증감',
 '재고자산의 증감',
 '매입채무 등의 증감',
 '기타',
 '순영업활동현금흐름(NCF)',
 '자본적지출',
 '잉여현금흐름(FCF)',
 '영업자산의처분',
 '투자자산의처분(net)',
 '기타(net)',
 '내부순현금흐름(ICF)',
 '기타 차입외조달(net)',
 '재무적가용현금흐름(ACF)',
 '매출액.1',
 'EBIT.1',
 'Op.EBIT.1',
 'EBITDA.1',
 '금융비용.1',
 '순금융비용.1',
 '세전계속사업이익.1',
 '당기순이익.1',
 '자산총계.1',
 '부채총계.1',
 '자본총계.1',
 '(납입자본금).1',
 '총차입금.1',
 '단기차입금.1',
 '유동성장기부채.1',
 '현금성자산.1',
 '순차입금.1',
 '조정총차입금.1',
 '운전자본.1',
 '매출채권.1',
 '재고자산.1',
 '매입채무.1',
 '총영업활동현금흐름(OCF).1',
 '비현금항목 조정.1',
 '운전자본투자.1',
 '매출채권 등의 증감.1',
 '재고자산의 증감.1',
 '매입채무 등의 증감.1',
 '기타.1',
 '순영업활동현금흐름(NCF).1',
 '자본적지출.1',
 '잉여현금흐름(FCF).1',
 '영업자산의처분.1',
 '투자자산의처분(net).1',
 '기타(net).1',
 '내부순현금흐름(ICF).1',
 '재무적가용현금흐름(ACF).1',
 '매출액.2',
 'EBIT.2',
 'Op.EBIT.2

In [ ]:
['매출액',
 'EBIT',
 'Op.EBIT',
 'EBITDA',
 '금융비용',
 '순금융비용',
 '세전계속사업이익',
 '당기순이익',
 '자산총계',
 '부채총계',
 '자본총계',
 '(납입자본금)',
 '총차입금',
 '단기차입금',
 '유동성장기부채',
 '장기차입금',
 '현금성자산',
 '순차입금',
 '조정총차입금',
 '운전자본',
 '매출채권',
 '재고자산',
 '매입채무',
 '총영업활동현금흐름(OCF)',
#  'EBITDA.1',
 '비현금항목 조정',
 '운전자본투자',
 '매출채권 등의 증감',
 '재고자산의 증감',
 '매입채무 등의 증감',
 '기타',
 '순영업활동현금흐름(NCF)',
 '자본적지출',
 '잉여현금흐름(FCF)',
 '영업자산의처분',
 '투자자산의처분(net)',
 '기타(net)',
 '내부순현금흐름(ICF)',
 '기타 차입외조달(net)',
 '재무적가용현금흐름(ACF)',
 '매출액.1',
 'EBIT.1',
 'Op.EBIT.1',
 'EBITDA.2',
 '금융비용.1',
 '순금융비용.1',
 '세전계속사업이익.1',
 '당기순이익.1',
 '자산총계.1',
 '부채총계.1',
 '자본총계.1',
 '(납입자본금).1',
 '총차입금.1',
 '단기차입금.1',
 '유동성장기부채.1',
#  '사채',
#  '장기차입금 등',
 '현금성자산.1',
 '순차입금.1',
 '조정총차입금.1',
 '운전자본.1',
 '매출채권.1',
 '재고자산.1',
 '매입채무.1',
 '총영업활동현금흐름(OCF).1',
#  'EBITDA.3',
 '비현금항목 조정.1',
 '운전자본투자.1',
 '매출채권 등의 증감.1',
 '재고자산의 증감.1',
 '매입채무 등의 증감.1',
 '기타.1',
 '순영업활동현금흐름(NCF).1',
 '자본적지출.1',
 '잉여현금흐름(FCF).1',
 '영업자산의처분.1',
 '투자자산의처분(net).1',
 '기타(net).1',
 '내부순현금흐름(ICF).1',
 '재무적가용현금흐름(ACF).1',
 '매출액.2',
 'EBIT.2',
 'Op.EBIT.2',
 'EBITDA.4',
 '금융비용.2',
 '순금융비용.2',
 '세전계속사업이익.2',
 '당기순이익.2',
 '자산총계.2',
 '부채총계.2',
 '자본총계.2',
 '(납입자본금).2',
 '총차입금.2',
 '단기차입금.2',
 '유동성장기부채.2',
#  '장기차입금 등.1',
 '현금성자산.2',
 '순차입금.2',
 '조정총차입금.2',
 '운전자본.2',
 '매출채권.2',
 '재고자산.2',
 '매입채무.2',
 '총영업활동현금흐름(OCF).2',
#  'EBITDA.5',
 '비현금항목 조정.2',
 '운전자본투자.2',
 '매출채권 등의 증감.2',
 '재고자산의 증감.2',
 '매입채무 등의 증감.2',
 '기타.2',
 '순영업활동현금흐름(NCF).2',
 '자본적지출.2',
 '잉여현금흐름(FCF).2',
 '영업자산의처분.2',
 '투자자산의처분(net).2',
 '기타(net).2',
 '내부순현금흐름(ICF).2',
 '재무적가용현금흐름(ACF).2',
#  '건전성 여부'
]

In [4]:
# 결측치 처리-보간법 이용
data = data.interpolate()
# 나머지 결측치-0으로 채워넣음
data = data.fillna(0)

In [5]:
np.save("data_company.npy",arr = data)
data = np.load("data_company.npy", allow_pickle=True)

In [6]:
# integer변환
x = data[0:,0:-1].astype('int64')
y = data[0:,-1]

# y분류 LabelEncoder로 숫자로 변경(0-건전, 1-부실)
encoder=LabelEncoder()
encoder.fit(y)
y_encode = encoder.transform(y)

In [7]:
print("x:",x)
print("y:",y_encode)

print("x.shape:",x.shape) #(150,135)
print("y.shape:",y.shape) #(150,)

x: [[ 36576  -8581  -9097 ...     47    457    439]
 [ 13967    311    281 ...     14    267    272]
 [129485   5140   5278 ...   -608  -3132  -3132]
 ...
 [ 18321    148    301 ...     29  -2453  -2452]
 [ 68075   5184   5191 ...   -198   -378   -378]
 [ 34259    711    164 ...   -198   -194   -194]]
y: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
x.shape: (139, 113)
y.shape: (139,)


In [8]:
#1. 데이터
x_train,x_test,y_train,y_test=train_test_split(x,y_encode,test_size=0.3,random_state=60)

print(x_train.shape)
print(x_test.shape)
print(y_train)

(97, 113)
(42, 113)
[1 0 1 0 1 0 0 0 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1
 0 0 0 1 1 0 0 0 1 1 1 1 0 0 1 1 0 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 1 0 0]


In [9]:
from sklearn.model_selection import GridSearchCV

In [10]:
#2. 모델
model = XGBClassifier(n_estimators=1000)
#3. 훈련, 평가예측
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
acc = model.score(x_test,y_test)
print("acc:",acc)

acc: 0.8095238095238095


In [11]:
feature_importances_ = model.feature_importances_

In [12]:
data = pd.read_csv("data_company22.csv",index_col=0, header=0, thousands=',',encoding='cp949')
index = data.iloc[:,:-1].columns

In [14]:
feature_importances = pd.DataFrame({'xgb_feature_importance':feature_importances_}, index=index)
feature_importances = feature_importances.sort_values(by=['xgb_feature_importance'],ascending=False)
feature_importances

xgb_feature_importance
금융비용                          0.120079
자본총계.2                        0.110507
순영업활동현금흐름(NCF)                0.070952
비현금항목 조정.1                    0.055309
매출액.2                         0.045530
...                                ...
잉여현금흐름(FCF).1                 0.000000
영업자산의처분.1                     0.000000
투자자산의처분(net).1                0.000000
기타(net).1                     0.000000
조정총차입금.1                      0.000000

[113 rows x 1 columns]

In [15]:
feature_importances.to_csv('./카카오뱅크/feature_importances.csv')

In [16]:
data = pd.read_csv("data_company22.csv",index_col=0, header=0, thousands=',',encoding='cp949')

In [17]:
data['건전성 여부'] = data['건전성 여부'].replace('부실',1).replace('건전',0)

In [19]:
corr = data.corr()

In [20]:
Survived = corr.loc[:,['건전성 여부']]
Survived = abs(Survived)
corelation = Survived.sort_values(by=['건전성 여부'],
                              ascending=False)
corelation = corelation[2:]
corelation

건전성 여부
총영업활동현금흐름(OCF).1  0.414318
현금성자산.1           0.383129
현금성자산.2           0.370028
현금성자산             0.365346
EBITDA.1          0.355322
...                    ...
순차입금.1            0.010839
금융비용.2            0.009324
금융비용              0.008855
비현금항목 조정.1        0.008548
내부순현금흐름(ICF).2    0.003742

[112 rows x 1 columns]

In [21]:
corelation.to_csv('./카카오뱅크/corelation.csv')

In [22]:
data_list = list(data)
data_list_0 = data_list[:39] # 49개임

In [24]:
df = pd.DataFrame(columns=['변수','점수'])
for i in data_list_0 :
    try:
        cor = corelation.loc[i][0]+corelation.loc[i+'.1'][0]+corelation.loc[i+'.2'][0]
        importance = feature_importances.loc[i][0]+feature_importances.loc[i+'.1'][0]+feature_importances.loc[i+'.2'][0]
        c = cor + (importance*2)
        dict = {'변수':[i],'점수':[c]}
        print(c)
        df = df.append(pd.DataFrame(dict))
    except: continue
df

0.7373564339921154
0.959062942391653
0.9551682373156356
1.0575332147307388
0.3355992559600639
0.4999845657092308
0.9266956574681027
0.8991728471147395
0.8040430731038986
0.5196764572940217
1.0730146703993664
0.5799301455294756
0.6377876385603134
0.5594304155560306
0.6137620738745433
1.275921374808113
0.07589060008690081
0.5985457138057919
0.5899467259834354
0.41358897764243563
0.5875012915785012
0.2921656740045172
0.3784995354441853
0.5397647072358361
0.35962651317002003
0.3058090833062413
0.29354095660306856
0.25151385315488334
0.8180039947493616
0.38326218534074796
0.30668518293270974
0.4071820113724662
0.3222418300723691
0.3397417892424709
0.15227325471841063
0.2350659536165529


변수        점수
0             매출액  0.737356
0            EBIT  0.959063
0         Op.EBIT  0.955168
0          EBITDA  1.057533
0            금융비용  0.335599
0           순금융비용  0.499985
0        세전계속사업이익  0.926696
0           당기순이익  0.899173
0            자산총계  0.804043
0            부채총계  0.519676
0            자본총계  1.073015
0         (납입자본금)  0.579930
0            총차입금  0.637788
0           단기차입금  0.559430
0         유동성장기부채  0.613762
0           현금성자산  1.275921
0            순차입금  0.075891
0          조정총차입금  0.598546
0            운전자본  0.589947
0            매출채권  0.413589
0            재고자산  0.587501
0            매입채무  0.292166
0        비현금항목 조정  0.378500
0          운전자본투자  0.539765
0      매출채권 등의 증감  0.359627
0        재고자산의 증감  0.305809
0      매입채무 등의 증감  0.293541
0              기타  0.251514
0  순영업활동현금흐름(NCF)  0.818004
0           자본적지출  0.383262
0     잉여현금흐름(FCF)  0.306685
0         영업자산의처분  0.407182
0    투자자산의처분(net)  0.322242
0         기타(net)  0.339742
0    내부순현금흐름(ICF)  0.152273
0  재무적가용현금흐름(ACF)  0.235066

In [25]:
score = df.sort_values(by=['점수'],
                              ascending=False)

In [26]:
순위 = list(range(1,len(score)+1))

In [27]:
score['순위'] = 순위

In [29]:
score = score[['순위','변수','점수']]
score

순위              변수        점수
0   1           현금성자산  1.275921
0   2            자본총계  1.073015
0   3          EBITDA  1.057533
0   4            EBIT  0.959063
0   5         Op.EBIT  0.955168
0   6        세전계속사업이익  0.926696
0   7           당기순이익  0.899173
0   8  순영업활동현금흐름(NCF)  0.818004
0   9            자산총계  0.804043
0  10             매출액  0.737356
0  11            총차입금  0.637788
0  12         유동성장기부채  0.613762
0  13          조정총차입금  0.598546
0  14            운전자본  0.589947
0  15            재고자산  0.587501
0  16         (납입자본금)  0.579930
0  17           단기차입금  0.559430
0  18          운전자본투자  0.539765
0  19            부채총계  0.519676
0  20           순금융비용  0.499985
0  21            매출채권  0.413589
0  22         영업자산의처분  0.407182
0  23           자본적지출  0.383262
0  24        비현금항목 조정  0.378500
0  25      매출채권 등의 증감  0.359627
0  26         기타(net)  0.339742
0  27            금융비용  0.335599
0  28    투자자산의처분(net)  0.322242
0  29     잉여현금흐름(FCF)  0.306685
0  30        재고자산의 증감  0.305809
0  31      매입채무 등의 증감  0.293541
0  32            매입채무  0.292166
0  33              기타  0.251514
0  34  재무적가용현금흐름(ACF)  0.235066
0  35    내부순현금흐름(ICF)  0.152273
0  36            순차입금  0.075891

In [30]:
score.to_csv('./카카오뱅크/score.csv')